/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-dim": "#699cff",
        "on-secondary-container": "#74a3ff",
        "primary-fixed-dim": "#c2a4ff",
        "on-tertiary-fixed": "#003640",
        background: "#070d1f",
        "secondary-container": "#002455",
        "surface-container-lowest": "#000000",
        "surface-container-high": "#131e3c",
        "primary-container": "#8342f4",
        outline: "#68749b",
        "error-dim": "#c8475d",
        "on-secondary": "#003d88",
        "on-primary": "#2b0065",
        "tertiary-container": "#53ddfc",
        "surface-container-highest": "#182446",
        "secondary-fixed": "#d8e2ff",
        "on-tertiary-fixed-variant": "#005564",
        "on-tertiary-container": "#004b58",
        "surface-dim": "#070d1f",
        "surface-bright": "#1c2a51",
        "tertiary-fixed": "#53ddfc",
        "inverse-on-surface": "#4f5469",
        tertiary: "#8ce7ff",
        "surface-container-low": "#0b1228",
        "on-error-container": "#ff97a3",
        "on-error": "#490013",
        secondary: "#adc6ff",
        "inverse-primary": "#742fe5",
        "on-secondary-fixed": "#003c86",
        "on-secondary-fixed-variant": "#0057bd",
        "tertiary-dim": "#40ceed",
        "primary-dim": "#8a4cfc",
        "on-surface-variant": "#9eaad3",
        error: "#fd6f85",
        "on-primary-fixed": "#340078",
        "inverse-surface": "#faf8ff",
        "error-container": "#8a1632",
        "surface-container": "#0f1832",
        "secondary-fixed-dim": "#c3d4ff",
        "surface-variant": "#182446",
        "primary-fixed": "#ceb5ff",
        "on-primary-fixed-variant": "#5800c2",
        "on-background": "#dfe4ff",
        surface: "#070d1f",
        "tertiary-fixed-dim": "#40ceed",
        "outline-variant": "#3b476b",
        "on-tertiary": "#005464",
        "on-surface": "#dfe4ff",
        "surface-tint": "#af88ff",
        primary: "#af88ff",
        "on-primary-container": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },

  plugins: [],
};
